[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-puzzles = {version = "0.1.0", path = "./aoc-puzzles"}
clap = "4.0"
chrono = "0.4"